PA Migration: Update docs
triton-inference-server/dali_backend pull request #254
Opened 2024-08-05 23:28 UTC by fpetrini15

Point PA to new repo

2024-08-06 10:34 UTC, szkarpinski requested changes
@fpetrini15 The new link appears to be broken (https://github.com/triton-inference-server/perf_analyzer/blob/main/README.md) and https://github.com/triton-inference-server/perf_analyzer/ repo seems not to be live yet.

Please let us know when it's there and we'll be happy to merge this. Thanks!

2024-08-06 10:57 UTC, mzient commented on benchmarks/BM_efficientnet/README.md
> +may be found in the [`perf_analyzer` documentation](https://github.com/triton-inference-server/perf_analyzer/blob/main/README.md).
The page does not exist.
https://github.com/triton-inference-server/perf_analyzer/blob/main/README.md

2024-08-06 16:37 UTC, fpetrini15 commented
Correct, the repo is still private. We are aiming to switch it to public shortly. I'll let you know when that happens!

2024-08-07 00:44 UTC, fpetrini15 commented
The repo is now public. Please check again.

2024-08-08 14:06 UTC, szkarpinski approved these changes

2024-08-08 15:31 UTC, fpetrini15 commented
@szkarpinski You'll have to merge as well. I am not authorized.

2024-08-08 15:37 UTC, merged